/**
 * GENERATED by scripts/generate-tokens.mjs from tokens/*.css — do not edit.
 * CSS is the source of truth (DESIGN-SYSTEM-001 DS-4); run `npm run tokens:generate`.
 */

export const REF_TOKENS = [
  '--dof-ref-accent-300',
  '--dof-ref-accent-500',
  '--dof-ref-accent-600',
  '--dof-ref-accent-700',
  '--dof-ref-border-hairline',
  '--dof-ref-border-strong',
  '--dof-ref-caution-300',
  '--dof-ref-caution-700',
  '--dof-ref-critical-300',
  '--dof-ref-critical-600',
  '--dof-ref-duration-celebration',
  '--dof-ref-duration-deliberate',
  '--dof-ref-duration-instant',
  '--dof-ref-duration-quick',
  '--dof-ref-ease-enter',
  '--dof-ref-ease-exit',
  '--dof-ref-ease-settle',
  '--dof-ref-ember-300',
  '--dof-ref-ember-500',
  '--dof-ref-ember-600',
  '--dof-ref-focus-ring-offset',
  '--dof-ref-focus-ring-width',
  '--dof-ref-info-300',
  '--dof-ref-info-600',
  '--dof-ref-neutral-0',
  '--dof-ref-neutral-100',
  '--dof-ref-neutral-200',
  '--dof-ref-neutral-300',
  '--dof-ref-neutral-400',
  '--dof-ref-neutral-450',
  '--dof-ref-neutral-50',
  '--dof-ref-neutral-500',
  '--dof-ref-neutral-600',
  '--dof-ref-neutral-700',
  '--dof-ref-neutral-800',
  '--dof-ref-neutral-900',
  '--dof-ref-neutral-950',
  '--dof-ref-opacity-disabled',
  '--dof-ref-opacity-hint',
  '--dof-ref-opacity-scrim',
  '--dof-ref-positive-300',
  '--dof-ref-positive-600',
  '--dof-ref-radius-1',
  '--dof-ref-radius-2',
  '--dof-ref-radius-3',
  '--dof-ref-shadow-overlay',
  '--dof-ref-shadow-raised',
  '--dof-ref-shadow-spotlight',
  '--dof-ref-target-min',
  '--dof-ref-text-body',
  '--dof-ref-text-caption',
  '--dof-ref-text-display',
  '--dof-ref-text-emphasis',
  '--dof-ref-text-headline',
  '--dof-ref-text-title',
  '--dof-ref-z-base',
  '--dof-ref-z-ceremony',
  '--dof-ref-z-overlay',
  '--dof-ref-z-sticky',
  '--dof-ref-z-toast',
] as const
export type RefToken = (typeof REF_TOKENS)[number]

export const SYS_TOKENS = [
  '--dof-sys-color-accent',
  '--dof-sys-color-accent-strong',
  '--dof-sys-color-caution',
  '--dof-sys-color-critical',
  '--dof-sys-color-ember',
  '--dof-sys-color-focus',
  '--dof-sys-color-info',
  '--dof-sys-color-line',
  '--dof-sys-color-on-accent',
  '--dof-sys-color-on-ember',
  '--dof-sys-color-positive',
  '--dof-sys-color-surface',
  '--dof-sys-color-surface-raised',
  '--dof-sys-color-surface-sunken',
  '--dof-sys-color-text',
  '--dof-sys-color-text-faint',
  '--dof-sys-color-text-muted',
  '--dof-sys-font-numeric',
  '--dof-sys-font-reading',
  '--dof-sys-font-ui',
  '--dof-sys-radius-large',
  '--dof-sys-radius-medium',
  '--dof-sys-radius-small',
] as const
export type SysToken = (typeof SYS_TOKENS)[number]

export const BRAND_TOKENS = [
  '--dof-brand-accent',
  '--dof-brand-accent-strong',
  '--dof-brand-font-reading',
  '--dof-brand-font-ui',
  '--dof-brand-line',
  '--dof-brand-on-accent',
  '--dof-brand-radius-large',
  '--dof-brand-radius-medium',
  '--dof-brand-radius-small',
  '--dof-brand-surface',
  '--dof-brand-surface-raised',
  '--dof-brand-surface-sunken',
  '--dof-brand-text',
  '--dof-brand-text-faint',
  '--dof-brand-text-muted',
] as const
export type BrandToken = (typeof BRAND_TOKENS)[number]

/** Tempo band values in ms — parsed from the CSS ref tokens (never hand-edited). */
export const DURATIONS_MS = {"instant":100,"quick":200,"deliberate":400,"celebration":1100} as const

/** `var(--dof-…)` reference for inline style bindings that must stay token-pure. */
export function cssVar(token: RefToken | SysToken | BrandToken): string {
  return `var(${token})`
}
