#!/usr/bin/env node
/**
 * Token generator (DESIGN-SYSTEM-001 DS-4): CSS is the source of truth.
 * Parses --dof-* custom properties out of tokens/*.css and emits
 * tokens.generated.ts (typed name lists + cssVar helper). A vitest sync test
 * regenerates and diffs, so drift between CSS and TS cannot merge.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = join(root, 'app/design-system/tokens')
const files = ['theme.css', 'scopes/workspace.css', 'scopes/storefront.css', 'scopes/marketplace.css', 'scopes/admin.css']

const names = new Set()
const durations = {}
for (const file of files) {
  const css = readFileSync(join(tokensDir, file), 'utf8')
  for (const match of css.matchAll(/(--dof-[a-z0-9-]+)\s*:/g)) names.add(match[1])
  // brand tokens are *consumed* (with fallbacks) in CSS and *set* at runtime — capture references
  for (const match of css.matchAll(/var\((--dof-brand-[a-z0-9-]+)/g)) names.add(match[1])
  // tempo band values feed the TS motion module — CSS stays the single source (DS-4)
  for (const match of css.matchAll(/--dof-ref-duration-([a-z]+)\s*:\s*(\d+)ms/g)) {
    durations[match[1]] = Number(match[2])
  }
}

const groups = { ref: [], sys: [], brand: [] }
for (const name of [...names].sort()) {
  if (name.startsWith('--dof-ref-')) groups.ref.push(name)
  else if (name.startsWith('--dof-sys-')) groups.sys.push(name)
  else if (name.startsWith('--dof-brand-')) groups.brand.push(name)
}

const list = (arr) => arr.map((n) => `  '${n}',`).join('\n')
const out = `/**
 * GENERATED by scripts/generate-tokens.mjs from tokens/*.css — do not edit.
 * CSS is the source of truth (DESIGN-SYSTEM-001 DS-4); run \`npm run tokens:generate\`.
 */

export const REF_TOKENS = [
${list(groups.ref)}
] as const
export type RefToken = (typeof REF_TOKENS)[number]

export const SYS_TOKENS = [
${list(groups.sys)}
] as const
export type SysToken = (typeof SYS_TOKENS)[number]

export const BRAND_TOKENS = [
${list(groups.brand)}
] as const
export type BrandToken = (typeof BRAND_TOKENS)[number]

/** Tempo band values in ms — parsed from the CSS ref tokens (never hand-edited). */
export const DURATIONS_MS = ${JSON.stringify(durations)} as const

/** \`var(--dof-…)\` reference for inline style bindings that must stay token-pure. */
export function cssVar(token: RefToken | SysToken | BrandToken): string {
  return \`var(\${token})\`
}
`

const target = join(tokensDir, 'tokens.generated.ts')
if (process.argv.includes('--check')) {
  let current = ''
  try { current = readFileSync(target, 'utf8') } catch { /* missing counts as drift */ }
  if (current !== out) {
    console.error('✗ tokens.generated.ts is out of sync with tokens/*.css — run `npm run tokens:generate`')
    process.exit(1)
  }
  console.log(`✓ tokens.generated.ts in sync (${groups.ref.length} ref, ${groups.sys.length} sys, ${groups.brand.length} brand)`)
} else {
  writeFileSync(target, out)
  console.log(`✓ generated tokens.generated.ts (${groups.ref.length} ref, ${groups.sys.length} sys, ${groups.brand.length} brand)`)
}
