#!/usr/bin/env node
/**
 * Icon subset generator (DESIGN-SYSTEM-001 DS-15): the curated Iconify subset is
 * compiled into the bundle at build time — no runtime icon fetching, ever.
 * Reads @iconify-json/lucide, extracts the names in ICON_NAMES (resolving aliases),
 * writes app/design-system/icons/icons.generated.ts. Adding an icon = adding a name
 * here and regenerating (goes through PR review like any component change).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

export const ICON_NAMES = [
  // actions
  'plus', 'pencil', 'trash-2', 'archive', 'archive-restore', 'copy', 'check', 'x',
  'undo-2', 'upload', 'download', 'send', 'share-2', 'external-link', 'refresh-cw',
  // navigation
  'chevron-down', 'chevron-up', 'chevron-left', 'chevron-right', 'arrow-left', 'arrow-right',
  'menu', 'search', 'settings', 'sliders-horizontal', 'ellipsis',
  // objects
  'package', 'shopping-bag', 'shopping-cart', 'tag', 'image', 'camera', 'store',
  'truck', 'rotate-ccw', 'box', 'layers', 'users', 'user', 'heart', 'star',
  // status & feedback
  'circle-alert', 'triangle-alert', 'circle-check', 'circle', 'info', 'circle-help', 'loader-circle',
  'eye', 'eye-off', 'lock', 'shield-check', 'badge-check', 'wifi-off', 'clock',
  // AI & moments
  'sparkles', 'lightbulb', 'flame', 'party-popper', 'trending-up', 'message-circle', 'mic',
]

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = JSON.parse(readFileSync(join(root, 'node_modules/@iconify-json/lucide/icons.json'), 'utf8'))

const icons = {}
const missing = []
for (const name of ICON_NAMES) {
  if (source.icons[name]) icons[name] = source.icons[name]
  else if (source.aliases?.[name]) {
    const parent = source.aliases[name].parent
    if (source.icons[parent]) icons[name] = source.icons[parent]
    else missing.push(name)
  } else missing.push(name)
}
if (missing.length > 0) {
  console.error(`✗ icons not found in lucide: ${missing.join(', ')}`)
  process.exit(1)
}

const subset = { prefix: 'dof', icons, width: source.width, height: source.height }
const out = `/**
 * GENERATED by scripts/generate-icons.mjs — curated Lucide subset, bundled offline
 * (DESIGN-SYSTEM-001 DS-15). Do not edit; add names to the generator and re-run.
 */
import type { IconifyJSON } from '@iconify/vue'

export const ICON_COLLECTION = ${JSON.stringify(subset)} as unknown as IconifyJSON

export const ICON_NAMES = [
${ICON_NAMES.map((n) => `  '${n}',`).join('\n')}
] as const
export type IconName = (typeof ICON_NAMES)[number]
`

mkdirSync(join(root, 'app/design-system/icons'), { recursive: true })
writeFileSync(join(root, 'app/design-system/icons/icons.generated.ts'), out)
console.log(`✓ generated icon subset (${ICON_NAMES.length} icons)`)
